//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuctionResult
    {
        public string fResultId { get; set; }
        public string fPostUserId { get; set; }
        public string fWinUserId { get; set; }
        public Nullable<int> fBidMoney { get; set; }
        public Nullable<int> fTotalMoney { get; set; }
        public Nullable<System.DateTime> fWinTime { get; set; }
        public Nullable<int> fBidCount { get; set; }
        public string fDeliveryInfo { get; set; }
    }
}
