//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tExchangeResult
    {
        public string fItemIdA { get; set; }
        public string fItemIdB { get; set; }
        public string fItemNameA { get; set; }
        public string fItemNameB { get; set; }
        public string fAPhoto0 { get; set; }
        public string fBPhoto0 { get; set; }
        public string fPostUserId { get; set; }
        public string fPostAccount { get; set; }
        public string fCoupleUserId { get; set; }
        public string fCoupleAccount { get; set; }
        public System.DateTime fSubmitTime { get; set; }
        public System.DateTime fEndTime { get; set; }
        public string fStatus { get; set; }
    }
}
